AllCops:
  TargetRubyVersion: 2.7.0
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'Rakefile'

Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true

Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
