default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV["APP_DATABASE_NAME"] %>
  username: <%= ENV["APP_DATABASE_USERNAME"] %>
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
  host: <%= ENV["APP_DATABASE_HOST"] %>

development:
  <<: *default

test:
  <<: *default
  database: app_test

production:
  <<: *default
